import local from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Toaster } from "react-hot-toast";
import { getCurrentUser } from "./actions/getCurrentUser";

const krooner = local({
  src: "../public/fonts/krooner.ttf",
  variable: "--font-krooner",
});

const satoshi = local({
  src: "../public/fonts/Satoshi-Variable.ttf",
});

export const metadata = {
  title: "Daily Beauty Blogs",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en" className={`${krooner.variable}`}>
      <body className={`${satoshi.className}`}>
        <Toaster />
        <Navbar currentUser={currentUser} />
        {children}
      </body>
    </html>
  );
}
